package projects.vendex.entities;

import jakarta.persistence.*;
import lombok.*;
import projects.vendex.enums.PurchaseOrderStatus;

import java.time.LocalDateTime;
import java.util.List;

@Entity
@Table(name = "purchase_orders")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PurchaseOrder {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // FINALIZED manufacturer (nullable until finalized)
    @ManyToOne
    @JoinColumn(name = "manufacturer_id")
    private Manufacturer manufacturer;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private PurchaseOrderStatus status;

    // AI confidence for this order decision
    private Double confidence;

    // Receipt generated by AI
    private String receiptUri;

    private LocalDateTime createdAt;
    private LocalDateTime approvedAt;
    private LocalDateTime sentAt;
    private LocalDateTime receivedAt;

    @OneToMany(mappedBy = "purchaseOrder", cascade = CascadeType.ALL)
    private List<PurchaseOrderItem> items;
}
