import json
from fpdf import FPDF

# 1. THE PDF GENERATOR CLASS
class ReceiptPDF(FPDF):
    def header(self):
        self.set_font("Arial", "B", 20)
        self.set_text_color(63, 81, 181) # Indigo Brand Color
        self.cell(0, 10, "VENDEX", ln=True, align="C")
        self.set_font("Arial", "", 10)
        self.set_text_color(0, 0, 0)
        self.cell(0, 5, "Official Purchase Order Receipt", ln=True, align="C")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()} - Generated by Vendex", align="C")

def create_receipt_pdf(data, filename="receipt.pdf"):
    pdf = ReceiptPDF()
    pdf.add_page()
    
    # --- PO & Manufacturer Info ---
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, f"Order Details", ln=True)
    pdf.set_font("Arial", "", 10)
    pdf.cell(100, 7, f"PO ID: {data['purchaseOrder']['purchaseOrderId']}")
    pdf.cell(0, 7, f"Date: {data['purchaseOrder']['createdAt']}", ln=True)
    pdf.ln(5)

    # --- Manufacturer Info box ---
    pdf.set_fill_color(245, 245, 245)
    pdf.rect(10, pdf.get_y(), 190, 25, 'F')
    pdf.set_x(15)
    pdf.set_font("Arial", "B", 10)
    pdf.cell(0, 7, f"To: {data['manufacturer']['name']}", ln=True)
    pdf.set_x(15)
    pdf.set_font("Arial", "", 10)
    pdf.cell(0, 6, f"Email: {data['manufacturer']['emailId']}", ln=True)
    pdf.set_x(15)
    pdf.cell(0, 6, f"Payment: {data['manufacturer']['paymentMode']} (Advance: {data['manufacturer']['advanceRequired']})", ln=True)
    pdf.ln(10)

    # --- Items Table ---
    pdf.set_font("Arial", "B", 10)
    pdf.set_fill_color(63, 81, 181)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(80, 10, " Item SKU", border=1, fill=True)
    pdf.cell(30, 10, " Quantity", border=1, fill=True)
    pdf.cell(40, 10, " Unit Cost", border=1, fill=True)
    pdf.cell(40, 10, " Total", border=1, fill=True, ln=True)

    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", "", 10)
    for item in data['items']:
        line_total = item['quantity'] * item['unitCost']
        pdf.cell(80, 10, f" {item['sku']}", border=1)
        pdf.cell(30, 10, f" {item['quantity']}", border=1)
        pdf.cell(40, 10, f" {item['unitCost']}", border=1)
        pdf.cell(40, 10, f" {line_total}", border=1, ln=True)

    # --- Totals ---
    pdf.ln(5)
    pdf.set_font("Arial", "B", 12)
    pdf.set_x(130)
    pdf.cell(30, 10, "Grand Total:", ln=False)
    pdf.cell(40, 10, f"Rs. {data['totals']['grandTotal']}", ln=True, align="R")

    pdf.output(filename)
    return filename